### PR TITLE
Change bool to Option<()> as a fallible return value

### LINKED ISSUE #12: Optional Stronger Error Reporting
It has been asked for IO operations to have a `Result` type.

However there's no result data to be had most of the time, so most results would be `Result<()`, and there's also no error information to be had most of the time, so we'd be using `Result<(),()>` everywhere.

Except that to be used with the `?` operator for early return at the moment, the error case needs to implement `Error`, so we need to use some custom type that we add an `Error` instance for, `Result<(),EasyCursesError>`. There's an RFC that'll help clear up that particular issue.

```
https://github.com/rust-lang/rust/issues/31436
```

I think the best way to do it would be to have a wrapper struct that called the inner methods, checked for false, and then returned an appropriate result. That way people start with the current `bool` and `Option` results, and then they can upgrade their usage to `Result` based types if they want to.

### PR DESCRIPTION
**Pull request by sollyucko**
Fixes #12

### CODE REVIEW

**Comment by Lokathor** [comment]
Looks like you'll have to increase the CI version in the appveyor file. I'd try 1.31 first, that's when the 2018 edition started.

**Comment by sollyucko** [comment]
Yay, both CI systems now pass/succeed.

**Comment by Lokathor** [comment]
Looks good. I'll merge it now. When I get back to my computer later I'll do a release so it's on crates.io.

**Comment by sollyucko** [comment]
Sounds good, thanks!

**Comment by Lokathor** [comment]
Released as `0.13`

**Pull request merged**
